// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SUMMS.Api.Data;

#nullable disable

namespace SUMMS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303120000_AddReservations")]
    partial class AddReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SUMMS.Api.Domain.Models.MobilityLocation", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<int>("AvailableSpots").HasColumnType("integer");
                    b.Property<int>("Capacity").HasColumnType("integer");
                    b.Property<string>("City").IsRequired().HasColumnType("text");
                    b.Property<double>("Latitude").HasColumnType("double precision");
                    b.Property<double>("Longitude").HasColumnType("double precision");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<string>("PlaceId").IsRequired().HasColumnType("text");
                    b.Property<string>("Type").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("MobilityLocations");
                });

            modelBuilder.Entity("SUMMS.Api.Domain.Models.Reservation", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("City").IsRequired().HasColumnType("text");
                    b.Property<int>("MobilityLocationId").HasColumnType("integer");
                    b.Property<DateTime>("ReservationTime").HasColumnType("timestamp with time zone");
                    b.Property<string>("Type").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("MobilityLocationId");
                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("YourProject.Models.User", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("SUMMS.Api.Domain.Models.Reservation", b =>
                {
                    b.HasOne("SUMMS.Api.Domain.Models.MobilityLocation", "MobilityLocation")
                        .WithMany("Reservations")
                        .HasForeignKey("MobilityLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("MobilityLocation");
                });

            modelBuilder.Entity("SUMMS.Api.Domain.Models.MobilityLocation", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
